# Generated by Django 4.0 on 2021-12-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_endereco_cliente_endereco_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='empresa',
            new_name='empresa_id',
        ),
        migrations.RenameField(
            model_name='notapromissoria',
            old_name='contrato',
            new_name='contrato_id',
        ),
    ]
