# Generated by Django 4.0 on 2021-12-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cliente_contrato_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notapromissoria',
            name='data_vencimento',
        ),
    ]
